Resources:
  # Notes DynamoDB Table
  NotesDynamoDBTable:
    Type: AWS::DynamoDB::Table
    # DeletionPolicy: Retain
    # https://seed.run/blog/how-to-prevent-accidentally-deleting-serverless-resources
    Properties:
      TableName: ${self:provider.environment.NOTES_TABLE}
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: noteId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: noteId
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
